### ISSUE TITLE
Broken link to EIP 4844 readiness checklist in Danksharding roadmap

### ISSUE THREAD

**Issue by supernovalx** [ethereum/ethereum-org-website#11786]
### Describe the bug

In the `Current progress` section of the [article](https://ethereum.org/en/roadmap/danksharding/), the link to [EIP 4844 readiness checklist(opens in a new tab)](https://github.com/ethereum/pm/blob/master/Breakout-Room/4844-readiness-checklist.md#client-implementation-status) is broken.

### To reproduce

1. Go to [https://ethereum.org/en/roadmap/danksharding/#current-progress](https://ethereum.org/en/roadmap/danksharding/#current-progress/)
2. Click on [EIP 4844 readiness checklist(opens in a new tab)](https://github.com/ethereum/pm/blob/master/Breakout-Room/4844-readiness-checklist.md#client-implementation-status)
3. See error

### Expected behavior

Correct link

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by NitinRana01125532553** [comment]
Hello, The link on the site correctly leads to https://eips.ethereum.org/EIPS/eip-4844 shard blob transactions, I think this issue has been fixed.

**Comment by b-wagn** [comment]
I think the link is still broken.
The correct link should probably be [this](https://github.com/ethereum/pm/blob/master/Dencun/4844-readiness-checklist.md).

**Comment by corwintines** [comment]
> I think the link is still broken. The correct link should probably be [this](https://github.com/ethereum/pm/blob/master/Dencun/4844-readiness-checklist.md).

This seems like the right link to me as well.
